### Get all todos
GET http://localhost:3000/todos

### Get a specific todo by ID
GET http://localhost:3000/todos/1

### Create a new todo
POST http://localhost:3000/todos
Content-Type: application/json

{
    "description": "Learn REST APIs",
    "category": "Learning",
    "expirationDate": "2025-04-30T00:00:00.000Z"
}

### Update a todo
PUT http://localhost:3000/todos/1
Content-Type: application/json

{
    "description": "Learn REST APIs",
    "category": "Learning",
    "expirationDate": "2025-04-30T00:00:00.000Z",
    "state": "done"
}

### Delete a todo
DELETE http://localhost:3000/todos/1