### Define a variable for the base URL
@baseUrl = http://localhost:3000

### Get all todos
GET {{baseUrl}}/todos

### Get a specific todo by ID
GET {{baseUrl}}/todos/1

### Create a new todo
POST {{baseUrl}}/todos
Content-Type: application/json

{
    "description": "Learn REST APIs",
    "category": "Learning",
    "expirationDate": "2025-04-30T00:00:00.000Z"
}

### Update a todo
PUT {{baseUrl}}/todos/1
Content-Type: application/json

{
    "description": "Learn REST APIs",
    "category": "Learning",
    "expirationDate": "2025-04-30T00:00:00.000Z",
    "state": "done"
}
### Delete a todo
DELETE {{baseUrl}}/todos/1